
#include "setting.h"



#ifndef __setting_config_h
#define __setting_config_h

/* Config setting attributes */
/* Config units */
#define SETTING_CONF_MINUTE_UNIT					"m"
#define SETTING_CONF_HOUR_UNIT						".00"
#define SETTING_CONF_DEGREE_UNIT					"d"
#define SETTING_CONF_PERCENT_UNIT					"%"
#define SETTING_CONF_DEGR_PER_MIN_UNIT				"d/m"
/* Config selector 1 */
#define SETTING_CONF_SELECTOR1_POS01				" LC"
#define SETTING_CONF_SELECTOR1_POS02				" rC"
#define SETTING_CONF_SELECTOR1_POS03				"???"
#define SETTING_CONF_SELECTOR1_POS04				"???"
#define SETTING_CONF_SELECTOR1_POS05				"???"
#define SETTING_CONF_SELECTOR1_POS06				"???"
#define SETTING_CONF_SELECTOR1_POS07				"???"
#define SETTING_CONF_SELECTOR1_POS08				"???"
#define SETTING_CONF_SELECTOR1_POS09				"???"
#define SETTING_CONF_SELECTOR1_POS10				"???"
#define SETTING_CONF_SELECTOR1_POS11				"???"
#define SETTING_CONF_SELECTOR1_POS12				"???"
#define SETTING_CONF_SELECTOR1_POS13				"???"
#define SETTING_CONF_SELECTOR1_POS14				"???"
#define SETTING_CONF_SELECTOR1_POS15				"???"
/* Config selector 2 */
#define SETTING_CONF_SELECTOR2_POS01				" c2"
#define SETTING_CONF_SELECTOR2_POS02				" c3"
#define SETTING_CONF_SELECTOR2_POS03				"???"
#define SETTING_CONF_SELECTOR2_POS04				"???"
#define SETTING_CONF_SELECTOR2_POS05				"???"
#define SETTING_CONF_SELECTOR2_POS06				"???"
#define SETTING_CONF_SELECTOR2_POS07				"???"
#define SETTING_CONF_SELECTOR2_POS08				"???"
#define SETTING_CONF_SELECTOR2_POS09				"???"
#define SETTING_CONF_SELECTOR2_POS10				"???"
#define SETTING_CONF_SELECTOR2_POS11				"???"
#define SETTING_CONF_SELECTOR2_POS12				"???"
#define SETTING_CONF_SELECTOR2_POS13				"???"
#define SETTING_CONF_SELECTOR2_POS14				"???"
#define SETTING_CONF_SELECTOR2_POS15				"???"
/* Config selector 3 */
#define SETTING_CONF_SELECTOR3_POS01				" F0"
#define SETTING_CONF_SELECTOR3_POS02				" F1"
#define SETTING_CONF_SELECTOR3_POS03				" F2"
#define SETTING_CONF_SELECTOR3_POS04				" F3"
#define SETTING_CONF_SELECTOR3_POS05				" F4"
#define SETTING_CONF_SELECTOR3_POS06				" F5"
#define SETTING_CONF_SELECTOR3_POS07				" F6"
#define SETTING_CONF_SELECTOR3_POS08				" F7"
#define SETTING_CONF_SELECTOR3_POS09				" F8"
#define SETTING_CONF_SELECTOR3_POS10				" F9"
#define SETTING_CONF_SELECTOR3_POS11				"F10"
#define SETTING_CONF_SELECTOR3_POS12				"F11"
#define SETTING_CONF_SELECTOR3_POS13				"F12"
#define SETTING_CONF_SELECTOR3_POS14				"???"
#define SETTING_CONF_SELECTOR3_POS15				"???"
/* Config selector 4 */
#define SETTING_CONF_SELECTOR4_POS01				" A0"
#define SETTING_CONF_SELECTOR4_POS02				" A1"
#define SETTING_CONF_SELECTOR4_POS03				" A2"
#define SETTING_CONF_SELECTOR4_POS04				" A3"
#define SETTING_CONF_SELECTOR4_POS05				" A4"
#define SETTING_CONF_SELECTOR4_POS06				" A5"
#define SETTING_CONF_SELECTOR4_POS07				" A6"
#define SETTING_CONF_SELECTOR4_POS08				" A7"
#define SETTING_CONF_SELECTOR4_POS09				" A8"
#define SETTING_CONF_SELECTOR4_POS10				" A9"
#define SETTING_CONF_SELECTOR4_POS11				"A10"
#define SETTING_CONF_SELECTOR4_POS12				"A11"
#define SETTING_CONF_SELECTOR4_POS13				"???"
#define SETTING_CONF_SELECTOR4_POS14				"???"
#define SETTING_CONF_SELECTOR4_POS15				"???"
/* Config selector 5 */
#define SETTING_CONF_SELECTOR5_POS01				"POS"
#define SETTING_CONF_SELECTOR5_POS02				"nEG"
#define SETTING_CONF_SELECTOR5_POS03				"???"
#define SETTING_CONF_SELECTOR5_POS04				"???"
#define SETTING_CONF_SELECTOR5_POS05				"???"
#define SETTING_CONF_SELECTOR5_POS06				"???"
#define SETTING_CONF_SELECTOR5_POS07				"???"
#define SETTING_CONF_SELECTOR5_POS08				"???"
#define SETTING_CONF_SELECTOR5_POS09				"???"
#define SETTING_CONF_SELECTOR5_POS10				"???"
#define SETTING_CONF_SELECTOR5_POS11				"???"
#define SETTING_CONF_SELECTOR5_POS12				"???"
#define SETTING_CONF_SELECTOR5_POS13				"???"
#define SETTING_CONF_SELECTOR5_POS14				"???"
#define SETTING_CONF_SELECTOR5_POS15				"???"
/* Config selector 6 */
#define SETTING_CONF_SELECTOR6_POS01				"  2"
#define SETTING_CONF_SELECTOR6_POS02				"  4"
#define SETTING_CONF_SELECTOR6_POS03				"  8"
#define SETTING_CONF_SELECTOR6_POS04				"???"
#define SETTING_CONF_SELECTOR6_POS05				"???"
#define SETTING_CONF_SELECTOR6_POS06				"???"
#define SETTING_CONF_SELECTOR6_POS07				"???"
#define SETTING_CONF_SELECTOR6_POS08				"???"
#define SETTING_CONF_SELECTOR6_POS09				"???"
#define SETTING_CONF_SELECTOR6_POS10				"???"
#define SETTING_CONF_SELECTOR6_POS11				"???"
#define SETTING_CONF_SELECTOR6_POS12				"???"
#define SETTING_CONF_SELECTOR6_POS13				"???"
#define SETTING_CONF_SELECTOR6_POS14				"???"
#define SETTING_CONF_SELECTOR6_POS15				"???"
/* Config selector 7 */
#define SETTING_CONF_SELECTOR7_POS01				"???"
#define SETTING_CONF_SELECTOR7_POS02				"???"
#define SETTING_CONF_SELECTOR7_POS03				"???"
#define SETTING_CONF_SELECTOR7_POS04				"???"
#define SETTING_CONF_SELECTOR7_POS05				"???"
#define SETTING_CONF_SELECTOR7_POS06				"???"
#define SETTING_CONF_SELECTOR7_POS07				"???"
#define SETTING_CONF_SELECTOR7_POS08				"???"
#define SETTING_CONF_SELECTOR7_POS09				"???"
#define SETTING_CONF_SELECTOR7_POS10				"???"
#define SETTING_CONF_SELECTOR7_POS11				"???"
#define SETTING_CONF_SELECTOR7_POS12				"???"
#define SETTING_CONF_SELECTOR7_POS13				"???"
#define SETTING_CONF_SELECTOR7_POS14				"???"
#define SETTING_CONF_SELECTOR7_POS15				"???"
/* Config selector 8 */
#define SETTING_CONF_SELECTOR8_POS01				"???"
#define SETTING_CONF_SELECTOR8_POS02				"???"
#define SETTING_CONF_SELECTOR8_POS03				"???"
#define SETTING_CONF_SELECTOR8_POS04				"???"
#define SETTING_CONF_SELECTOR8_POS05				"???"
#define SETTING_CONF_SELECTOR8_POS06				"???"
#define SETTING_CONF_SELECTOR8_POS07				"???"
#define SETTING_CONF_SELECTOR8_POS08				"???"
#define SETTING_CONF_SELECTOR8_POS09				"???"
#define SETTING_CONF_SELECTOR8_POS10				"???"
#define SETTING_CONF_SELECTOR8_POS11				"???"
#define SETTING_CONF_SELECTOR8_POS12				"???"
#define SETTING_CONF_SELECTOR8_POS13				"???"
#define SETTING_CONF_SELECTOR8_POS14				"???"
#define SETTING_CONF_SELECTOR8_POS15				"???"



/*
 * Setting configuration explanation
 *
 * ********************************************************************************************************************************
 * @field TYPE specifies setting type, must be member of SETTING_Type enumerator
 * @field MIN specifies absolute minimum value of the setting
 * @field DEF specifies default value of the setting
 * @field MAX specifies absolute maximum value of the setting
 * @field STEP specifies the step of changing setting
 * @field LIMIT_TYPE specifies the type of dynamic limitation of the setting value, must be member of SETTING_LimitType enumerator
 * @field LOWER_LIMITER specifies the number of setting in array the value of which determine lower dynamic limit
 * @field UPPER_LIMITER specifies the number of setting in array the value of which determine upper dynamic limit
 *
 * @note If dynamic limiting is enabled, the maximum or minimum setting value determines not only by the MAX or MIN field,
 *       but also by the value of the lower or upper limiters.
 * ********************************************************************************************************************************
 */

/* Config setting array 01 */
/** Setting 01
  * @name Acceleration time */
#define SETTING_CONF_ARRAY01_SET01_TYPE				SETTING_INTEGER_UNITLESS
#define SETTING_CONF_ARRAY01_SET01_MIN 				3
#define SETTING_CONF_ARRAY01_SET01_DEF 				10
#define SETTING_CONF_ARRAY01_SET01_MAX				300
#define SETTING_CONF_ARRAY01_SET01_STEP				1
#define SETTING_CONF_ARRAY01_SET01_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY01_SET01_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY01_SET01_UPPER_LIMITER	0
/** Setting 02
  * @name Deceleration time */
#define SETTING_CONF_ARRAY01_SET02_TYPE				SETTING_INTEGER_UNITLESS
#define SETTING_CONF_ARRAY01_SET02_MIN 				3
#define SETTING_CONF_ARRAY01_SET02_DEF 				10
#define SETTING_CONF_ARRAY01_SET02_MAX				300
#define SETTING_CONF_ARRAY01_SET02_STEP				1
#define SETTING_CONF_ARRAY01_SET02_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY01_SET02_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY01_SET02_UPPER_LIMITER	0
/** Setting 03
  * @name Low speed */
#define SETTING_CONF_ARRAY01_SET03_TYPE				SETTING_1_DECIMAL_UNITLESS
#define SETTING_CONF_ARRAY01_SET03_MIN 				50
#define SETTING_CONF_ARRAY01_SET03_DEF 				50
#define SETTING_CONF_ARRAY01_SET03_MAX				500
#define SETTING_CONF_ARRAY01_SET03_STEP				1
#define SETTING_CONF_ARRAY01_SET03_LIMIT_TYPE		SETTING_UPPER_LIMIT
#define SETTING_CONF_ARRAY01_SET03_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY01_SET03_UPPER_LIMITER	5
/** Setting 04
  * @name High speed */
#define SETTING_CONF_ARRAY01_SET04_TYPE				SETTING_1_DECIMAL_UNITLESS
#define SETTING_CONF_ARRAY01_SET04_MIN 				50
#define SETTING_CONF_ARRAY01_SET04_DEF 				500
#define SETTING_CONF_ARRAY01_SET04_MAX				600
#define SETTING_CONF_ARRAY01_SET04_STEP				1
#define SETTING_CONF_ARRAY01_SET04_LIMIT_TYPE		SETTING_LOWER_LIMIT
#define SETTING_CONF_ARRAY01_SET04_LOWER_LIMITER	6
#define SETTING_CONF_ARRAY01_SET04_UPPER_LIMITER	0
/** Setting 05
  * @name Preset speed 1 */
#define SETTING_CONF_ARRAY01_SET05_TYPE				SETTING_1_DECIMAL_UNITLESS
#define SETTING_CONF_ARRAY01_SET05_MIN 				50
#define SETTING_CONF_ARRAY01_SET05_DEF 				250
#define SETTING_CONF_ARRAY01_SET05_MAX				500
#define SETTING_CONF_ARRAY01_SET05_STEP				1
#define SETTING_CONF_ARRAY01_SET05_LIMIT_TYPE		SETTING_FULL_LIMIT
#define SETTING_CONF_ARRAY01_SET05_LOWER_LIMITER	3
#define SETTING_CONF_ARRAY01_SET05_UPPER_LIMITER	6
/** Setting 06
  * @name Preset speed 2 */
#define SETTING_CONF_ARRAY01_SET06_TYPE				SETTING_1_DECIMAL_UNITLESS
#define SETTING_CONF_ARRAY01_SET06_MIN 				50
#define SETTING_CONF_ARRAY01_SET06_DEF 				500
#define SETTING_CONF_ARRAY01_SET06_MAX				500
#define SETTING_CONF_ARRAY01_SET06_STEP				1
#define SETTING_CONF_ARRAY01_SET06_LIMIT_TYPE		SETTING_FULL_LIMIT
#define SETTING_CONF_ARRAY01_SET06_LOWER_LIMITER	5
#define SETTING_CONF_ARRAY01_SET06_UPPER_LIMITER	4
/** Setting 07
  * @name Motor nominal frequency */
#define SETTING_CONF_ARRAY01_SET07_TYPE				SETTING_INTEGER_UNITLESS
#define SETTING_CONF_ARRAY01_SET07_MIN 				50
#define SETTING_CONF_ARRAY01_SET07_DEF 				50
#define SETTING_CONF_ARRAY01_SET07_MAX				60
#define SETTING_CONF_ARRAY01_SET07_STEP				10
#define SETTING_CONF_ARRAY01_SET07_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY01_SET07_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY01_SET07_UPPER_LIMITER	0
/** Setting 08
  * @name Motor nominal voltage */
#define SETTING_CONF_ARRAY01_SET08_TYPE				SETTING_INTEGER_UNITLESS
#define SETTING_CONF_ARRAY01_SET08_MIN 				200
#define SETTING_CONF_ARRAY01_SET08_DEF 				380
#define SETTING_CONF_ARRAY01_SET08_MAX				480
#define SETTING_CONF_ARRAY01_SET08_STEP				10
#define SETTING_CONF_ARRAY01_SET08_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY01_SET08_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY01_SET08_UPPER_LIMITER	0
/** Setting 09
  * @name Motor nominal current */
#define SETTING_CONF_ARRAY01_SET09_TYPE				SETTING_2_DECIMAL_UNITLESS
#define SETTING_CONF_ARRAY01_SET09_MIN 				20
#define SETTING_CONF_ARRAY01_SET09_DEF 				650
#define SETTING_CONF_ARRAY01_SET09_MAX				750
#define SETTING_CONF_ARRAY01_SET09_STEP				1
#define SETTING_CONF_ARRAY01_SET09_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY01_SET09_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY01_SET09_UPPER_LIMITER	0
/** Setting 10
  * @name Motor thermal current */
#define SETTING_CONF_ARRAY01_SET10_TYPE				SETTING_2_DECIMAL_UNITLESS
#define SETTING_CONF_ARRAY01_SET10_MIN 				20
#define SETTING_CONF_ARRAY01_SET10_DEF 				650
#define SETTING_CONF_ARRAY01_SET10_MAX				750
#define SETTING_CONF_ARRAY01_SET10_STEP				1
#define SETTING_CONF_ARRAY01_SET10_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY01_SET10_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY01_SET10_UPPER_LIMITER	0
/** Setting 11
  * @name Cutoff current ratio */
#define SETTING_CONF_ARRAY01_SET11_TYPE				SETTING_1_DECIMAL_UNITLESS
#define SETTING_CONF_ARRAY01_SET11_MIN 				11
#define SETTING_CONF_ARRAY01_SET11_DEF 				15
#define SETTING_CONF_ARRAY01_SET11_MAX				20
#define SETTING_CONF_ARRAY01_SET11_STEP				1
#define SETTING_CONF_ARRAY01_SET11_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY01_SET11_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY01_SET11_UPPER_LIMITER	0
/** Setting 12
  * @name Brake DC voltage */
#define SETTING_CONF_ARRAY01_SET12_TYPE				SETTING_INTEGER_UNITLESS
#define SETTING_CONF_ARRAY01_SET12_MIN 				5
#define SETTING_CONF_ARRAY01_SET12_DEF 				5
#define SETTING_CONF_ARRAY01_SET12_MAX				100
#define SETTING_CONF_ARRAY01_SET12_STEP				1
#define SETTING_CONF_ARRAY01_SET12_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY01_SET12_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY01_SET12_UPPER_LIMITER	0
/** Setting 13
  * @name Brake time */
#define SETTING_CONF_ARRAY01_SET13_TYPE				SETTING_1_DECIMAL_UNITLESS
#define SETTING_CONF_ARRAY01_SET13_MIN 				1
#define SETTING_CONF_ARRAY01_SET13_DEF 				10
#define SETTING_CONF_ARRAY01_SET13_MAX				300
#define SETTING_CONF_ARRAY01_SET13_STEP				1
#define SETTING_CONF_ARRAY01_SET13_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY01_SET13_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY01_SET13_UPPER_LIMITER	0
/** Setting 14
  * @name Free run time */
#define SETTING_CONF_ARRAY01_SET14_TYPE				SETTING_INTEGER_UNITLESS
#define SETTING_CONF_ARRAY01_SET14_MIN 				1
#define SETTING_CONF_ARRAY01_SET14_DEF 				300
#define SETTING_CONF_ARRAY01_SET14_MAX				1800
#define SETTING_CONF_ARRAY01_SET14_STEP				1
#define SETTING_CONF_ARRAY01_SET14_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY01_SET14_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY01_SET14_UPPER_LIMITER	0
/** Setting 15
  * @name Control location */
#define SETTING_CONF_ARRAY01_SET15_TYPE				SETTING_SELECTOR_TYPE_1
#define SETTING_CONF_ARRAY01_SET15_MIN 				0
#define SETTING_CONF_ARRAY01_SET15_DEF 				0
#define SETTING_CONF_ARRAY01_SET15_MAX				1
#define SETTING_CONF_ARRAY01_SET15_STEP				1
#define SETTING_CONF_ARRAY01_SET15_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY01_SET15_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY01_SET15_UPPER_LIMITER	0
/** Setting 16
  * @name Control scheme */
#define SETTING_CONF_ARRAY01_SET16_TYPE				SETTING_SELECTOR_TYPE_2
#define SETTING_CONF_ARRAY01_SET16_MIN 				0
#define SETTING_CONF_ARRAY01_SET16_DEF 				1
#define SETTING_CONF_ARRAY01_SET16_MAX				1
#define SETTING_CONF_ARRAY01_SET16_STEP				1
#define SETTING_CONF_ARRAY01_SET16_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY01_SET16_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY01_SET16_UPPER_LIMITER	0
/** Setting 17
  * @name Input 4 function */
#define SETTING_CONF_ARRAY01_SET17_TYPE				SETTING_SELECTOR_TYPE_3
#define SETTING_CONF_ARRAY01_SET17_MIN 				0
#define SETTING_CONF_ARRAY01_SET17_DEF 				1
#define SETTING_CONF_ARRAY01_SET17_MAX				12
#define SETTING_CONF_ARRAY01_SET17_STEP				1
#define SETTING_CONF_ARRAY01_SET17_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY01_SET17_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY01_SET17_UPPER_LIMITER	0
/** Setting 18
  * @name Input 5 function */
#define SETTING_CONF_ARRAY01_SET18_TYPE				SETTING_SELECTOR_TYPE_3
#define SETTING_CONF_ARRAY01_SET18_MIN 				0
#define SETTING_CONF_ARRAY01_SET18_DEF 				2
#define SETTING_CONF_ARRAY01_SET18_MAX				12
#define SETTING_CONF_ARRAY01_SET18_STEP				1
#define SETTING_CONF_ARRAY01_SET18_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY01_SET18_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY01_SET18_UPPER_LIMITER	0
/** Setting 19
  * @name Input 6 function */
#define SETTING_CONF_ARRAY01_SET19_TYPE				SETTING_SELECTOR_TYPE_3
#define SETTING_CONF_ARRAY01_SET19_MIN 				0
#define SETTING_CONF_ARRAY01_SET19_DEF 				5
#define SETTING_CONF_ARRAY01_SET19_MAX				12
#define SETTING_CONF_ARRAY01_SET19_STEP				1
#define SETTING_CONF_ARRAY01_SET19_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY01_SET19_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY01_SET19_UPPER_LIMITER	0
/** Setting 20
  * @name Relay signal */
#define SETTING_CONF_ARRAY01_SET20_TYPE				SETTING_SELECTOR_TYPE_4
#define SETTING_CONF_ARRAY01_SET20_MIN 				0
#define SETTING_CONF_ARRAY01_SET20_DEF 				1
#define SETTING_CONF_ARRAY01_SET20_MAX				11
#define SETTING_CONF_ARRAY01_SET20_STEP				1
#define SETTING_CONF_ARRAY01_SET20_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY01_SET20_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY01_SET20_UPPER_LIMITER	0
/** Setting 21
  * @name Relay delay */
#define SETTING_CONF_ARRAY01_SET21_TYPE				SETTING_1_DECIMAL_UNITLESS
#define SETTING_CONF_ARRAY01_SET21_MIN 				0
#define SETTING_CONF_ARRAY01_SET21_DEF 				0
#define SETTING_CONF_ARRAY01_SET21_MAX				100
#define SETTING_CONF_ARRAY01_SET21_STEP				1
#define SETTING_CONF_ARRAY01_SET21_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY01_SET21_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY01_SET21_UPPER_LIMITER	0
/** Setting 22
  * @name Relay behavior */
#define SETTING_CONF_ARRAY01_SET22_TYPE				SETTING_SELECTOR_TYPE_5
#define SETTING_CONF_ARRAY01_SET22_MIN 				0
#define SETTING_CONF_ARRAY01_SET22_DEF 				0
#define SETTING_CONF_ARRAY01_SET22_MAX				1
#define SETTING_CONF_ARRAY01_SET22_STEP				1
#define SETTING_CONF_ARRAY01_SET22_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY01_SET22_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY01_SET22_UPPER_LIMITER	0
/** Setting 23
  * @name Inverter pulse rate */
#define SETTING_CONF_ARRAY01_SET23_TYPE				SETTING_SELECTOR_TYPE_6
#define SETTING_CONF_ARRAY01_SET23_MIN 				0
#define SETTING_CONF_ARRAY01_SET23_DEF 				2
#define SETTING_CONF_ARRAY01_SET23_MAX				2
#define SETTING_CONF_ARRAY01_SET23_STEP				1
#define SETTING_CONF_ARRAY01_SET23_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY01_SET23_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY01_SET23_UPPER_LIMITER	0
/** Setting 24
  * @name Reserved */
#define SETTING_CONF_ARRAY01_SET24_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY01_SET24_MIN 				0
#define SETTING_CONF_ARRAY01_SET24_DEF 				1
#define SETTING_CONF_ARRAY01_SET24_MAX				20
#define SETTING_CONF_ARRAY01_SET24_STEP				1
#define SETTING_CONF_ARRAY01_SET24_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY01_SET24_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY01_SET24_UPPER_LIMITER	0



/* Config setting array 02 */
/** Setting 01
  * @name Reserved */
#define SETTING_CONF_ARRAY02_SET01_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY02_SET01_MIN 				0
#define SETTING_CONF_ARRAY02_SET01_DEF 				1
#define SETTING_CONF_ARRAY02_SET01_MAX				20
#define SETTING_CONF_ARRAY02_SET01_STEP				1
#define SETTING_CONF_ARRAY02_SET01_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY02_SET01_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY02_SET01_UPPER_LIMITER	0
/** Setting 02
  * @name Reserved */
#define SETTING_CONF_ARRAY02_SET02_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY02_SET02_MIN 				0
#define SETTING_CONF_ARRAY02_SET02_DEF 				1
#define SETTING_CONF_ARRAY02_SET02_MAX				20
#define SETTING_CONF_ARRAY02_SET02_STEP				1
#define SETTING_CONF_ARRAY02_SET02_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY02_SET02_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY02_SET02_UPPER_LIMITER	0
/** Setting 03
  * @name Reserved */
#define SETTING_CONF_ARRAY02_SET03_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY02_SET03_MIN 				0
#define SETTING_CONF_ARRAY02_SET03_DEF 				1
#define SETTING_CONF_ARRAY02_SET03_MAX				20
#define SETTING_CONF_ARRAY02_SET03_STEP				1
#define SETTING_CONF_ARRAY02_SET03_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY02_SET03_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY02_SET03_UPPER_LIMITER	0
/** Setting 04
  * @name Reserved */
#define SETTING_CONF_ARRAY02_SET04_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY02_SET04_MIN 				0
#define SETTING_CONF_ARRAY02_SET04_DEF 				1
#define SETTING_CONF_ARRAY02_SET04_MAX				20
#define SETTING_CONF_ARRAY02_SET04_STEP				1
#define SETTING_CONF_ARRAY02_SET04_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY02_SET04_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY02_SET04_UPPER_LIMITER	0
/** Setting 05
  * @name Reserved */
#define SETTING_CONF_ARRAY02_SET05_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY02_SET05_MIN 				0
#define SETTING_CONF_ARRAY02_SET05_DEF 				1
#define SETTING_CONF_ARRAY02_SET05_MAX				20
#define SETTING_CONF_ARRAY02_SET05_STEP				1
#define SETTING_CONF_ARRAY02_SET05_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY02_SET05_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY02_SET05_UPPER_LIMITER	0
/** Setting 06
  * @name Reserved */
#define SETTING_CONF_ARRAY02_SET06_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY02_SET06_MIN 				0
#define SETTING_CONF_ARRAY02_SET06_DEF 				1
#define SETTING_CONF_ARRAY02_SET06_MAX				20
#define SETTING_CONF_ARRAY02_SET06_STEP				1
#define SETTING_CONF_ARRAY02_SET06_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY02_SET06_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY02_SET06_UPPER_LIMITER	0
/** Setting 07
  * @name Reserved */
#define SETTING_CONF_ARRAY02_SET07_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY02_SET07_MIN 				0
#define SETTING_CONF_ARRAY02_SET07_DEF 				1
#define SETTING_CONF_ARRAY02_SET07_MAX				20
#define SETTING_CONF_ARRAY02_SET07_STEP				1
#define SETTING_CONF_ARRAY02_SET07_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY02_SET07_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY02_SET07_UPPER_LIMITER	0
/** Setting 08
  * @name Reserved */
#define SETTING_CONF_ARRAY02_SET08_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY02_SET08_MIN 				0
#define SETTING_CONF_ARRAY02_SET08_DEF 				1
#define SETTING_CONF_ARRAY02_SET08_MAX				20
#define SETTING_CONF_ARRAY02_SET08_STEP				1
#define SETTING_CONF_ARRAY02_SET08_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY02_SET08_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY02_SET08_UPPER_LIMITER	0
/** Setting 09
  * @name Reserved */
#define SETTING_CONF_ARRAY02_SET09_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY02_SET09_MIN 				0
#define SETTING_CONF_ARRAY02_SET09_DEF 				1
#define SETTING_CONF_ARRAY02_SET09_MAX				20
#define SETTING_CONF_ARRAY02_SET09_STEP				1
#define SETTING_CONF_ARRAY02_SET09_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY02_SET09_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY02_SET09_UPPER_LIMITER	0
/** Setting 10
  * @name Reserved */
#define SETTING_CONF_ARRAY02_SET10_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY02_SET10_MIN 				0
#define SETTING_CONF_ARRAY02_SET10_DEF 				1
#define SETTING_CONF_ARRAY02_SET10_MAX				20
#define SETTING_CONF_ARRAY02_SET10_STEP				1
#define SETTING_CONF_ARRAY02_SET10_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY02_SET10_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY02_SET10_UPPER_LIMITER	0
/** Setting 11
  * @name Reserved */
#define SETTING_CONF_ARRAY02_SET11_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY02_SET11_MIN 				0
#define SETTING_CONF_ARRAY02_SET11_DEF 				1
#define SETTING_CONF_ARRAY02_SET11_MAX				20
#define SETTING_CONF_ARRAY02_SET11_STEP				1
#define SETTING_CONF_ARRAY02_SET11_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY02_SET11_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY02_SET11_UPPER_LIMITER	0
/** Setting 12
  * @name Reserved */
#define SETTING_CONF_ARRAY02_SET12_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY02_SET12_MIN 				0
#define SETTING_CONF_ARRAY02_SET12_DEF 				1
#define SETTING_CONF_ARRAY02_SET12_MAX				20
#define SETTING_CONF_ARRAY02_SET12_STEP				1
#define SETTING_CONF_ARRAY02_SET12_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY02_SET12_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY02_SET12_UPPER_LIMITER	0
/** Setting 13
  * @name Reserved */
#define SETTING_CONF_ARRAY02_SET13_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY02_SET13_MIN 				0
#define SETTING_CONF_ARRAY02_SET13_DEF 				1
#define SETTING_CONF_ARRAY02_SET13_MAX				20
#define SETTING_CONF_ARRAY02_SET13_STEP				1
#define SETTING_CONF_ARRAY02_SET13_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY02_SET13_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY02_SET13_UPPER_LIMITER	0
/** Setting 14
  * @name Reserved */
#define SETTING_CONF_ARRAY02_SET14_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY02_SET14_MIN 				0
#define SETTING_CONF_ARRAY02_SET14_DEF 				1
#define SETTING_CONF_ARRAY02_SET14_MAX				20
#define SETTING_CONF_ARRAY02_SET14_STEP				1
#define SETTING_CONF_ARRAY02_SET14_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY02_SET14_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY02_SET14_UPPER_LIMITER	0
/** Setting 15
  * @name Reserved */
#define SETTING_CONF_ARRAY02_SET15_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY02_SET15_MIN 				0
#define SETTING_CONF_ARRAY02_SET15_DEF 				1
#define SETTING_CONF_ARRAY02_SET15_MAX				20
#define SETTING_CONF_ARRAY02_SET15_STEP				1
#define SETTING_CONF_ARRAY02_SET15_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY02_SET15_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY02_SET15_UPPER_LIMITER	0
/** Setting 16
  * @name Reserved */
#define SETTING_CONF_ARRAY02_SET16_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY02_SET16_MIN 				0
#define SETTING_CONF_ARRAY02_SET16_DEF 				1
#define SETTING_CONF_ARRAY02_SET16_MAX				20
#define SETTING_CONF_ARRAY02_SET16_STEP				1
#define SETTING_CONF_ARRAY02_SET16_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY02_SET16_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY02_SET16_UPPER_LIMITER	0
/** Setting 17
  * @name Reserved */
#define SETTING_CONF_ARRAY02_SET17_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY02_SET17_MIN 				0
#define SETTING_CONF_ARRAY02_SET17_DEF 				1
#define SETTING_CONF_ARRAY02_SET17_MAX				20
#define SETTING_CONF_ARRAY02_SET17_STEP				1
#define SETTING_CONF_ARRAY02_SET17_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY02_SET17_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY02_SET17_UPPER_LIMITER	0
/** Setting 18
  * @name Reserved */
#define SETTING_CONF_ARRAY02_SET18_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY02_SET18_MIN 				0
#define SETTING_CONF_ARRAY02_SET18_DEF 				1
#define SETTING_CONF_ARRAY02_SET18_MAX				20
#define SETTING_CONF_ARRAY02_SET18_STEP				1
#define SETTING_CONF_ARRAY02_SET18_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY02_SET18_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY02_SET18_UPPER_LIMITER	0
/** Setting 19
  * @name Reserved */
#define SETTING_CONF_ARRAY02_SET19_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY02_SET19_MIN 				0
#define SETTING_CONF_ARRAY02_SET19_DEF 				1
#define SETTING_CONF_ARRAY02_SET19_MAX				20
#define SETTING_CONF_ARRAY02_SET19_STEP				1
#define SETTING_CONF_ARRAY02_SET19_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY02_SET19_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY02_SET19_UPPER_LIMITER	0
/** Setting 20
  * @name Reserved */
#define SETTING_CONF_ARRAY02_SET20_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY02_SET20_MIN 				0
#define SETTING_CONF_ARRAY02_SET20_DEF 				1
#define SETTING_CONF_ARRAY02_SET20_MAX				20
#define SETTING_CONF_ARRAY02_SET20_STEP				1
#define SETTING_CONF_ARRAY02_SET20_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY02_SET20_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY02_SET20_UPPER_LIMITER	0
/** Setting 21
  * @name Reserved */
#define SETTING_CONF_ARRAY02_SET21_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY02_SET21_MIN 				0
#define SETTING_CONF_ARRAY02_SET21_DEF 				1
#define SETTING_CONF_ARRAY02_SET21_MAX				20
#define SETTING_CONF_ARRAY02_SET21_STEP				1
#define SETTING_CONF_ARRAY02_SET21_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY02_SET21_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY02_SET21_UPPER_LIMITER	0
/** Setting 22
  * @name Reserved */
#define SETTING_CONF_ARRAY02_SET22_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY02_SET22_MIN 				0
#define SETTING_CONF_ARRAY02_SET22_DEF 				1
#define SETTING_CONF_ARRAY02_SET22_MAX				20
#define SETTING_CONF_ARRAY02_SET22_STEP				1
#define SETTING_CONF_ARRAY02_SET22_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY02_SET22_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY02_SET22_UPPER_LIMITER	0
/** Setting 23
  * @name Reserved */
#define SETTING_CONF_ARRAY02_SET23_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY02_SET23_MIN 				0
#define SETTING_CONF_ARRAY02_SET23_DEF 				1
#define SETTING_CONF_ARRAY02_SET23_MAX				20
#define SETTING_CONF_ARRAY02_SET23_STEP				1
#define SETTING_CONF_ARRAY02_SET23_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY02_SET23_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY02_SET23_UPPER_LIMITER	0
/** Setting 24
  * @name Reserved */
#define SETTING_CONF_ARRAY02_SET24_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY02_SET24_MIN 				0
#define SETTING_CONF_ARRAY02_SET24_DEF 				1
#define SETTING_CONF_ARRAY02_SET24_MAX				20
#define SETTING_CONF_ARRAY02_SET24_STEP				1
#define SETTING_CONF_ARRAY02_SET24_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY02_SET24_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY02_SET24_UPPER_LIMITER	0



/* Config setting array 03 */
/** Setting 01
  * @name Reserved */
#define SETTING_CONF_ARRAY03_SET01_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY03_SET01_MIN 				0
#define SETTING_CONF_ARRAY03_SET01_DEF 				1
#define SETTING_CONF_ARRAY03_SET01_MAX				20
#define SETTING_CONF_ARRAY03_SET01_STEP				1
#define SETTING_CONF_ARRAY03_SET01_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY03_SET01_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY03_SET01_UPPER_LIMITER	0
/** Setting 02
  * @name Reserved */
#define SETTING_CONF_ARRAY03_SET02_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY03_SET02_MIN 				0
#define SETTING_CONF_ARRAY03_SET02_DEF 				1
#define SETTING_CONF_ARRAY03_SET02_MAX				20
#define SETTING_CONF_ARRAY03_SET02_STEP				1
#define SETTING_CONF_ARRAY03_SET02_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY03_SET02_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY03_SET02_UPPER_LIMITER	0
/** Setting 03
  * @name Reserved */
#define SETTING_CONF_ARRAY03_SET03_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY03_SET03_MIN 				0
#define SETTING_CONF_ARRAY03_SET03_DEF 				1
#define SETTING_CONF_ARRAY03_SET03_MAX				20
#define SETTING_CONF_ARRAY03_SET03_STEP				1
#define SETTING_CONF_ARRAY03_SET03_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY03_SET03_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY03_SET03_UPPER_LIMITER	0
/** Setting 04
  * @name Reserved */
#define SETTING_CONF_ARRAY03_SET04_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY03_SET04_MIN 				0
#define SETTING_CONF_ARRAY03_SET04_DEF 				1
#define SETTING_CONF_ARRAY03_SET04_MAX				20
#define SETTING_CONF_ARRAY03_SET04_STEP				1
#define SETTING_CONF_ARRAY03_SET04_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY03_SET04_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY03_SET04_UPPER_LIMITER	0
/** Setting 05
  * @name Reserved */
#define SETTING_CONF_ARRAY03_SET05_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY03_SET05_MIN 				0
#define SETTING_CONF_ARRAY03_SET05_DEF 				1
#define SETTING_CONF_ARRAY03_SET05_MAX				20
#define SETTING_CONF_ARRAY03_SET05_STEP				1
#define SETTING_CONF_ARRAY03_SET05_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY03_SET05_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY03_SET05_UPPER_LIMITER	0
/** Setting 06
  * @name Reserved */
#define SETTING_CONF_ARRAY03_SET06_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY03_SET06_MIN 				0
#define SETTING_CONF_ARRAY03_SET06_DEF 				1
#define SETTING_CONF_ARRAY03_SET06_MAX				20
#define SETTING_CONF_ARRAY03_SET06_STEP				1
#define SETTING_CONF_ARRAY03_SET06_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY03_SET06_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY03_SET06_UPPER_LIMITER	0
/** Setting 07
  * @name Reserved */
#define SETTING_CONF_ARRAY03_SET07_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY03_SET07_MIN 				0
#define SETTING_CONF_ARRAY03_SET07_DEF 				1
#define SETTING_CONF_ARRAY03_SET07_MAX				20
#define SETTING_CONF_ARRAY03_SET07_STEP				1
#define SETTING_CONF_ARRAY03_SET07_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY03_SET07_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY03_SET07_UPPER_LIMITER	0
/** Setting 08
  * @name Reserved */
#define SETTING_CONF_ARRAY03_SET08_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY03_SET08_MIN 				0
#define SETTING_CONF_ARRAY03_SET08_DEF 				1
#define SETTING_CONF_ARRAY03_SET08_MAX				20
#define SETTING_CONF_ARRAY03_SET08_STEP				1
#define SETTING_CONF_ARRAY03_SET08_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY03_SET08_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY03_SET08_UPPER_LIMITER	0
/** Setting 09
  * @name Reserved */
#define SETTING_CONF_ARRAY03_SET09_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY03_SET09_MIN 				0
#define SETTING_CONF_ARRAY03_SET09_DEF 				1
#define SETTING_CONF_ARRAY03_SET09_MAX				20
#define SETTING_CONF_ARRAY03_SET09_STEP				1
#define SETTING_CONF_ARRAY03_SET09_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY03_SET09_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY03_SET09_UPPER_LIMITER	0
/** Setting 10
  * @name Reserved */
#define SETTING_CONF_ARRAY03_SET10_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY03_SET10_MIN 				0
#define SETTING_CONF_ARRAY03_SET10_DEF 				1
#define SETTING_CONF_ARRAY03_SET10_MAX				20
#define SETTING_CONF_ARRAY03_SET10_STEP				1
#define SETTING_CONF_ARRAY03_SET10_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY03_SET10_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY03_SET10_UPPER_LIMITER	0
/** Setting 11
  * @name Reserved */
#define SETTING_CONF_ARRAY03_SET11_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY03_SET11_MIN 				0
#define SETTING_CONF_ARRAY03_SET11_DEF 				1
#define SETTING_CONF_ARRAY03_SET11_MAX				20
#define SETTING_CONF_ARRAY03_SET11_STEP				1
#define SETTING_CONF_ARRAY03_SET11_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY03_SET11_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY03_SET11_UPPER_LIMITER	0
/** Setting 12
  * @name Reserved */
#define SETTING_CONF_ARRAY03_SET12_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY03_SET12_MIN 				0
#define SETTING_CONF_ARRAY03_SET12_DEF 				1
#define SETTING_CONF_ARRAY03_SET12_MAX				20
#define SETTING_CONF_ARRAY03_SET12_STEP				1
#define SETTING_CONF_ARRAY03_SET12_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY03_SET12_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY03_SET12_UPPER_LIMITER	0
/** Setting 13
  * @name Reserved */
#define SETTING_CONF_ARRAY03_SET13_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY03_SET13_MIN 				0
#define SETTING_CONF_ARRAY03_SET13_DEF 				1
#define SETTING_CONF_ARRAY03_SET13_MAX				20
#define SETTING_CONF_ARRAY03_SET13_STEP				1
#define SETTING_CONF_ARRAY03_SET13_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY03_SET13_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY03_SET13_UPPER_LIMITER	0
/** Setting 14
  * @name Reserved */
#define SETTING_CONF_ARRAY03_SET14_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY03_SET14_MIN 				0
#define SETTING_CONF_ARRAY03_SET14_DEF 				1
#define SETTING_CONF_ARRAY03_SET14_MAX				20
#define SETTING_CONF_ARRAY03_SET14_STEP				1
#define SETTING_CONF_ARRAY03_SET14_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY03_SET14_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY03_SET14_UPPER_LIMITER	0
/** Setting 15
  * @name Reserved */
#define SETTING_CONF_ARRAY03_SET15_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY03_SET15_MIN 				0
#define SETTING_CONF_ARRAY03_SET15_DEF 				1
#define SETTING_CONF_ARRAY03_SET15_MAX				20
#define SETTING_CONF_ARRAY03_SET15_STEP				1
#define SETTING_CONF_ARRAY03_SET15_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY03_SET15_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY03_SET15_UPPER_LIMITER	0
/** Setting 16
  * @name Reserved */
#define SETTING_CONF_ARRAY03_SET16_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY03_SET16_MIN 				0
#define SETTING_CONF_ARRAY03_SET16_DEF 				1
#define SETTING_CONF_ARRAY03_SET16_MAX				20
#define SETTING_CONF_ARRAY03_SET16_STEP				1
#define SETTING_CONF_ARRAY03_SET16_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY03_SET16_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY03_SET16_UPPER_LIMITER	0
/** Setting 17
  * @name Reserved */
#define SETTING_CONF_ARRAY03_SET17_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY03_SET17_MIN 				0
#define SETTING_CONF_ARRAY03_SET17_DEF 				1
#define SETTING_CONF_ARRAY03_SET17_MAX				20
#define SETTING_CONF_ARRAY03_SET17_STEP				1
#define SETTING_CONF_ARRAY03_SET17_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY03_SET17_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY03_SET17_UPPER_LIMITER	0
/** Setting 18
  * @name Reserved */
#define SETTING_CONF_ARRAY03_SET18_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY03_SET18_MIN 				0
#define SETTING_CONF_ARRAY03_SET18_DEF 				1
#define SETTING_CONF_ARRAY03_SET18_MAX				20
#define SETTING_CONF_ARRAY03_SET18_STEP				1
#define SETTING_CONF_ARRAY03_SET18_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY03_SET18_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY03_SET18_UPPER_LIMITER	0
/** Setting 19
  * @name Reserved */
#define SETTING_CONF_ARRAY03_SET19_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY03_SET19_MIN 				0
#define SETTING_CONF_ARRAY03_SET19_DEF 				1
#define SETTING_CONF_ARRAY03_SET19_MAX				20
#define SETTING_CONF_ARRAY03_SET19_STEP				1
#define SETTING_CONF_ARRAY03_SET19_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY03_SET19_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY03_SET19_UPPER_LIMITER	0
/** Setting 20
  * @name Reserved */
#define SETTING_CONF_ARRAY03_SET20_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY03_SET20_MIN 				0
#define SETTING_CONF_ARRAY03_SET20_DEF 				1
#define SETTING_CONF_ARRAY03_SET20_MAX				20
#define SETTING_CONF_ARRAY03_SET20_STEP				1
#define SETTING_CONF_ARRAY03_SET20_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY03_SET20_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY03_SET20_UPPER_LIMITER	0
/** Setting 21
  * @name Reserved */
#define SETTING_CONF_ARRAY03_SET21_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY03_SET21_MIN 				0
#define SETTING_CONF_ARRAY03_SET21_DEF 				1
#define SETTING_CONF_ARRAY03_SET21_MAX				20
#define SETTING_CONF_ARRAY03_SET21_STEP				1
#define SETTING_CONF_ARRAY03_SET21_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY03_SET21_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY03_SET21_UPPER_LIMITER	0
/** Setting 22
  * @name Reserved */
#define SETTING_CONF_ARRAY03_SET22_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY03_SET22_MIN 				0
#define SETTING_CONF_ARRAY03_SET22_DEF 				1
#define SETTING_CONF_ARRAY03_SET22_MAX				20
#define SETTING_CONF_ARRAY03_SET22_STEP				1
#define SETTING_CONF_ARRAY03_SET22_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY03_SET22_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY03_SET22_UPPER_LIMITER	0
/** Setting 23
  * @name Reserved */
#define SETTING_CONF_ARRAY03_SET23_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY03_SET23_MIN 				0
#define SETTING_CONF_ARRAY03_SET23_DEF 				1
#define SETTING_CONF_ARRAY03_SET23_MAX				20
#define SETTING_CONF_ARRAY03_SET23_STEP				1
#define SETTING_CONF_ARRAY03_SET23_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY03_SET23_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY03_SET23_UPPER_LIMITER	0
/** Setting 24
  * @name Reserved */
#define SETTING_CONF_ARRAY03_SET24_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY03_SET24_MIN 				0
#define SETTING_CONF_ARRAY03_SET24_DEF 				1
#define SETTING_CONF_ARRAY03_SET24_MAX				20
#define SETTING_CONF_ARRAY03_SET24_STEP				1
#define SETTING_CONF_ARRAY03_SET24_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY03_SET24_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY03_SET24_UPPER_LIMITER	0



/* Config setting array 04 */
/** Setting 01
  * @name Reserved */
#define SETTING_CONF_ARRAY04_SET01_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY04_SET01_MIN 				0
#define SETTING_CONF_ARRAY04_SET01_DEF 				1
#define SETTING_CONF_ARRAY04_SET01_MAX				20
#define SETTING_CONF_ARRAY04_SET01_STEP				1
#define SETTING_CONF_ARRAY04_SET01_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY04_SET01_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY04_SET01_UPPER_LIMITER	0
/** Setting 02
  * @name Reserved */
#define SETTING_CONF_ARRAY04_SET02_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY04_SET02_MIN 				0
#define SETTING_CONF_ARRAY04_SET02_DEF 				1
#define SETTING_CONF_ARRAY04_SET02_MAX				20
#define SETTING_CONF_ARRAY04_SET02_STEP				1
#define SETTING_CONF_ARRAY04_SET02_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY04_SET02_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY04_SET02_UPPER_LIMITER	0
/** Setting 03
  * @name Reserved */
#define SETTING_CONF_ARRAY04_SET03_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY04_SET03_MIN 				0
#define SETTING_CONF_ARRAY04_SET03_DEF 				1
#define SETTING_CONF_ARRAY04_SET03_MAX				20
#define SETTING_CONF_ARRAY04_SET03_STEP				1
#define SETTING_CONF_ARRAY04_SET03_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY04_SET03_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY04_SET03_UPPER_LIMITER	0
/** Setting 04
  * @name Reserved */
#define SETTING_CONF_ARRAY04_SET04_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY04_SET04_MIN 				0
#define SETTING_CONF_ARRAY04_SET04_DEF 				1
#define SETTING_CONF_ARRAY04_SET04_MAX				20
#define SETTING_CONF_ARRAY04_SET04_STEP				1
#define SETTING_CONF_ARRAY04_SET04_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY04_SET04_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY04_SET04_UPPER_LIMITER	0
/** Setting 05
  * @name Reserved */
#define SETTING_CONF_ARRAY04_SET05_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY04_SET05_MIN 				0
#define SETTING_CONF_ARRAY04_SET05_DEF 				1
#define SETTING_CONF_ARRAY04_SET05_MAX				20
#define SETTING_CONF_ARRAY04_SET05_STEP				1
#define SETTING_CONF_ARRAY04_SET05_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY04_SET05_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY04_SET05_UPPER_LIMITER	0
/** Setting 06
  * @name Reserved */
#define SETTING_CONF_ARRAY04_SET06_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY04_SET06_MIN 				0
#define SETTING_CONF_ARRAY04_SET06_DEF 				1
#define SETTING_CONF_ARRAY04_SET06_MAX				20
#define SETTING_CONF_ARRAY04_SET06_STEP				1
#define SETTING_CONF_ARRAY04_SET06_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY04_SET06_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY04_SET06_UPPER_LIMITER	0
/** Setting 07
  * @name Reserved */
#define SETTING_CONF_ARRAY04_SET07_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY04_SET07_MIN 				0
#define SETTING_CONF_ARRAY04_SET07_DEF 				1
#define SETTING_CONF_ARRAY04_SET07_MAX				20
#define SETTING_CONF_ARRAY04_SET07_STEP				1
#define SETTING_CONF_ARRAY04_SET07_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY04_SET07_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY04_SET07_UPPER_LIMITER	0
/** Setting 08
  * @name Reserved */
#define SETTING_CONF_ARRAY04_SET08_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY04_SET08_MIN 				0
#define SETTING_CONF_ARRAY04_SET08_DEF 				1
#define SETTING_CONF_ARRAY04_SET08_MAX				20
#define SETTING_CONF_ARRAY04_SET08_STEP				1
#define SETTING_CONF_ARRAY04_SET08_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY04_SET08_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY04_SET08_UPPER_LIMITER	0
/** Setting 09
  * @name Reserved */
#define SETTING_CONF_ARRAY04_SET09_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY04_SET09_MIN 				0
#define SETTING_CONF_ARRAY04_SET09_DEF 				1
#define SETTING_CONF_ARRAY04_SET09_MAX				20
#define SETTING_CONF_ARRAY04_SET09_STEP				1
#define SETTING_CONF_ARRAY04_SET09_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY04_SET09_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY04_SET09_UPPER_LIMITER	0
/** Setting 10
  * @name Reserved */
#define SETTING_CONF_ARRAY04_SET10_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY04_SET10_MIN 				0
#define SETTING_CONF_ARRAY04_SET10_DEF 				1
#define SETTING_CONF_ARRAY04_SET10_MAX				20
#define SETTING_CONF_ARRAY04_SET10_STEP				1
#define SETTING_CONF_ARRAY04_SET10_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY04_SET10_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY04_SET10_UPPER_LIMITER	0
/** Setting 11
  * @name Reserved */
#define SETTING_CONF_ARRAY04_SET11_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY04_SET11_MIN 				0
#define SETTING_CONF_ARRAY04_SET11_DEF 				1
#define SETTING_CONF_ARRAY04_SET11_MAX				20
#define SETTING_CONF_ARRAY04_SET11_STEP				1
#define SETTING_CONF_ARRAY04_SET11_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY04_SET11_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY04_SET11_UPPER_LIMITER	0
/** Setting 12
  * @name Reserved */
#define SETTING_CONF_ARRAY04_SET12_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY04_SET12_MIN 				0
#define SETTING_CONF_ARRAY04_SET12_DEF 				1
#define SETTING_CONF_ARRAY04_SET12_MAX				20
#define SETTING_CONF_ARRAY04_SET12_STEP				1
#define SETTING_CONF_ARRAY04_SET12_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY04_SET12_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY04_SET12_UPPER_LIMITER	0
/** Setting 13
  * @name Reserved */
#define SETTING_CONF_ARRAY04_SET13_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY04_SET13_MIN 				0
#define SETTING_CONF_ARRAY04_SET13_DEF 				1
#define SETTING_CONF_ARRAY04_SET13_MAX				20
#define SETTING_CONF_ARRAY04_SET13_STEP				1
#define SETTING_CONF_ARRAY04_SET13_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY04_SET13_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY04_SET13_UPPER_LIMITER	0
/** Setting 14
  * @name Reserved */
#define SETTING_CONF_ARRAY04_SET14_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY04_SET14_MIN 				0
#define SETTING_CONF_ARRAY04_SET14_DEF 				1
#define SETTING_CONF_ARRAY04_SET14_MAX				20
#define SETTING_CONF_ARRAY04_SET14_STEP				1
#define SETTING_CONF_ARRAY04_SET14_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY04_SET14_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY04_SET14_UPPER_LIMITER	0
/** Setting 15
  * @name Reserved */
#define SETTING_CONF_ARRAY04_SET15_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY04_SET15_MIN 				0
#define SETTING_CONF_ARRAY04_SET15_DEF 				1
#define SETTING_CONF_ARRAY04_SET15_MAX				20
#define SETTING_CONF_ARRAY04_SET15_STEP				1
#define SETTING_CONF_ARRAY04_SET15_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY04_SET15_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY04_SET15_UPPER_LIMITER	0
/** Setting 16
  * @name Reserved */
#define SETTING_CONF_ARRAY04_SET16_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY04_SET16_MIN 				0
#define SETTING_CONF_ARRAY04_SET16_DEF 				1
#define SETTING_CONF_ARRAY04_SET16_MAX				20
#define SETTING_CONF_ARRAY04_SET16_STEP				1
#define SETTING_CONF_ARRAY04_SET16_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY04_SET16_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY04_SET16_UPPER_LIMITER	0
/** Setting 17
  * @name Reserved */
#define SETTING_CONF_ARRAY04_SET17_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY04_SET17_MIN 				0
#define SETTING_CONF_ARRAY04_SET17_DEF 				1
#define SETTING_CONF_ARRAY04_SET17_MAX				20
#define SETTING_CONF_ARRAY04_SET17_STEP				1
#define SETTING_CONF_ARRAY04_SET17_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY04_SET17_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY04_SET17_UPPER_LIMITER	0
/** Setting 18
  * @name Reserved */
#define SETTING_CONF_ARRAY04_SET18_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY04_SET18_MIN 				0
#define SETTING_CONF_ARRAY04_SET18_DEF 				1
#define SETTING_CONF_ARRAY04_SET18_MAX				20
#define SETTING_CONF_ARRAY04_SET18_STEP				1
#define SETTING_CONF_ARRAY04_SET18_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY04_SET18_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY04_SET18_UPPER_LIMITER	0
/** Setting 19
  * @name Reserved */
#define SETTING_CONF_ARRAY04_SET19_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY04_SET19_MIN 				0
#define SETTING_CONF_ARRAY04_SET19_DEF 				1
#define SETTING_CONF_ARRAY04_SET19_MAX				20
#define SETTING_CONF_ARRAY04_SET19_STEP				1
#define SETTING_CONF_ARRAY04_SET19_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY04_SET19_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY04_SET19_UPPER_LIMITER	0
/** Setting 20
  * @name Reserved */
#define SETTING_CONF_ARRAY04_SET20_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY04_SET20_MIN 				0
#define SETTING_CONF_ARRAY04_SET20_DEF 				1
#define SETTING_CONF_ARRAY04_SET20_MAX				20
#define SETTING_CONF_ARRAY04_SET20_STEP				1
#define SETTING_CONF_ARRAY04_SET20_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY04_SET20_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY04_SET20_UPPER_LIMITER	0
/** Setting 21
  * @name Reserved */
#define SETTING_CONF_ARRAY04_SET21_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY04_SET21_MIN 				0
#define SETTING_CONF_ARRAY04_SET21_DEF 				1
#define SETTING_CONF_ARRAY04_SET21_MAX				20
#define SETTING_CONF_ARRAY04_SET21_STEP				1
#define SETTING_CONF_ARRAY04_SET21_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY04_SET21_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY04_SET21_UPPER_LIMITER	0
/** Setting 22
  * @name Reserved */
#define SETTING_CONF_ARRAY04_SET22_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY04_SET22_MIN 				0
#define SETTING_CONF_ARRAY04_SET22_DEF 				1
#define SETTING_CONF_ARRAY04_SET22_MAX				20
#define SETTING_CONF_ARRAY04_SET22_STEP				1
#define SETTING_CONF_ARRAY04_SET22_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY04_SET22_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY04_SET22_UPPER_LIMITER	0
/** Setting 23
  * @name Reserved */
#define SETTING_CONF_ARRAY04_SET23_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY04_SET23_MIN 				0
#define SETTING_CONF_ARRAY04_SET23_DEF 				1
#define SETTING_CONF_ARRAY04_SET23_MAX				20
#define SETTING_CONF_ARRAY04_SET23_STEP				1
#define SETTING_CONF_ARRAY04_SET23_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY04_SET23_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY04_SET23_UPPER_LIMITER	0
/** Setting 24
  * @name Reserved */
#define SETTING_CONF_ARRAY04_SET24_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY04_SET24_MIN 				0
#define SETTING_CONF_ARRAY04_SET24_DEF 				1
#define SETTING_CONF_ARRAY04_SET24_MAX				20
#define SETTING_CONF_ARRAY04_SET24_STEP				1
#define SETTING_CONF_ARRAY04_SET24_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY04_SET24_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY04_SET24_UPPER_LIMITER	0



/* Config setting array 05 */
/** Setting 01
  * @name Reserved */
#define SETTING_CONF_ARRAY05_SET01_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY05_SET01_MIN 				0
#define SETTING_CONF_ARRAY05_SET01_DEF 				1
#define SETTING_CONF_ARRAY05_SET01_MAX				20
#define SETTING_CONF_ARRAY05_SET01_STEP				1
#define SETTING_CONF_ARRAY05_SET01_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY05_SET01_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY05_SET01_UPPER_LIMITER	0
/** Setting 02
  * @name Reserved */
#define SETTING_CONF_ARRAY05_SET02_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY05_SET02_MIN 				0
#define SETTING_CONF_ARRAY05_SET02_DEF 				1
#define SETTING_CONF_ARRAY05_SET02_MAX				20
#define SETTING_CONF_ARRAY05_SET02_STEP				1
#define SETTING_CONF_ARRAY05_SET02_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY05_SET02_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY05_SET02_UPPER_LIMITER	0
/** Setting 03
  * @name Reserved */
#define SETTING_CONF_ARRAY05_SET03_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY05_SET03_MIN 				0
#define SETTING_CONF_ARRAY05_SET03_DEF 				1
#define SETTING_CONF_ARRAY05_SET03_MAX				20
#define SETTING_CONF_ARRAY05_SET03_STEP				1
#define SETTING_CONF_ARRAY05_SET03_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY05_SET03_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY05_SET03_UPPER_LIMITER	0
/** Setting 04
  * @name Reserved */
#define SETTING_CONF_ARRAY05_SET04_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY05_SET04_MIN 				0
#define SETTING_CONF_ARRAY05_SET04_DEF 				1
#define SETTING_CONF_ARRAY05_SET04_MAX				20
#define SETTING_CONF_ARRAY05_SET04_STEP				1
#define SETTING_CONF_ARRAY05_SET04_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY05_SET04_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY05_SET04_UPPER_LIMITER	0
/** Setting 05
  * @name Reserved */
#define SETTING_CONF_ARRAY05_SET05_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY05_SET05_MIN 				0
#define SETTING_CONF_ARRAY05_SET05_DEF 				1
#define SETTING_CONF_ARRAY05_SET05_MAX				20
#define SETTING_CONF_ARRAY05_SET05_STEP				1
#define SETTING_CONF_ARRAY05_SET05_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY05_SET05_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY05_SET05_UPPER_LIMITER	0
/** Setting 06
  * @name Reserved */
#define SETTING_CONF_ARRAY05_SET06_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY05_SET06_MIN 				0
#define SETTING_CONF_ARRAY05_SET06_DEF 				1
#define SETTING_CONF_ARRAY05_SET06_MAX				20
#define SETTING_CONF_ARRAY05_SET06_STEP				1
#define SETTING_CONF_ARRAY05_SET06_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY05_SET06_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY05_SET06_UPPER_LIMITER	0
/** Setting 07
  * @name Reserved */
#define SETTING_CONF_ARRAY05_SET07_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY05_SET07_MIN 				0
#define SETTING_CONF_ARRAY05_SET07_DEF 				1
#define SETTING_CONF_ARRAY05_SET07_MAX				20
#define SETTING_CONF_ARRAY05_SET07_STEP				1
#define SETTING_CONF_ARRAY05_SET07_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY05_SET07_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY05_SET07_UPPER_LIMITER	0
/** Setting 08
  * @name Reserved */
#define SETTING_CONF_ARRAY05_SET08_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY05_SET08_MIN 				0
#define SETTING_CONF_ARRAY05_SET08_DEF 				1
#define SETTING_CONF_ARRAY05_SET08_MAX				20
#define SETTING_CONF_ARRAY05_SET08_STEP				1
#define SETTING_CONF_ARRAY05_SET08_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY05_SET08_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY05_SET08_UPPER_LIMITER	0
/** Setting 09
  * @name Reserved */
#define SETTING_CONF_ARRAY05_SET09_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY05_SET09_MIN 				0
#define SETTING_CONF_ARRAY05_SET09_DEF 				1
#define SETTING_CONF_ARRAY05_SET09_MAX				20
#define SETTING_CONF_ARRAY05_SET09_STEP				1
#define SETTING_CONF_ARRAY05_SET09_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY05_SET09_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY05_SET09_UPPER_LIMITER	0
/** Setting 10
  * @name Reserved */
#define SETTING_CONF_ARRAY05_SET10_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY05_SET10_MIN 				0
#define SETTING_CONF_ARRAY05_SET10_DEF 				1
#define SETTING_CONF_ARRAY05_SET10_MAX				20
#define SETTING_CONF_ARRAY05_SET10_STEP				1
#define SETTING_CONF_ARRAY05_SET10_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY05_SET10_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY05_SET10_UPPER_LIMITER	0
/** Setting 11
  * @name Reserved */
#define SETTING_CONF_ARRAY05_SET11_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY05_SET11_MIN 				0
#define SETTING_CONF_ARRAY05_SET11_DEF 				1
#define SETTING_CONF_ARRAY05_SET11_MAX				20
#define SETTING_CONF_ARRAY05_SET11_STEP				1
#define SETTING_CONF_ARRAY05_SET11_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY05_SET11_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY05_SET11_UPPER_LIMITER	0
/** Setting 12
  * @name Reserved */
#define SETTING_CONF_ARRAY05_SET12_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY05_SET12_MIN 				0
#define SETTING_CONF_ARRAY05_SET12_DEF 				1
#define SETTING_CONF_ARRAY05_SET12_MAX				20
#define SETTING_CONF_ARRAY05_SET12_STEP				1
#define SETTING_CONF_ARRAY05_SET12_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY05_SET12_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY05_SET12_UPPER_LIMITER	0
/** Setting 13
  * @name Reserved */
#define SETTING_CONF_ARRAY05_SET13_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY05_SET13_MIN 				0
#define SETTING_CONF_ARRAY05_SET13_DEF 				1
#define SETTING_CONF_ARRAY05_SET13_MAX				20
#define SETTING_CONF_ARRAY05_SET13_STEP				1
#define SETTING_CONF_ARRAY05_SET13_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY05_SET13_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY05_SET13_UPPER_LIMITER	0
/** Setting 14
  * @name Reserved */
#define SETTING_CONF_ARRAY05_SET14_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY05_SET14_MIN 				0
#define SETTING_CONF_ARRAY05_SET14_DEF 				1
#define SETTING_CONF_ARRAY05_SET14_MAX				20
#define SETTING_CONF_ARRAY05_SET14_STEP				1
#define SETTING_CONF_ARRAY05_SET14_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY05_SET14_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY05_SET14_UPPER_LIMITER	0
/** Setting 15
  * @name Reserved */
#define SETTING_CONF_ARRAY05_SET15_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY05_SET15_MIN 				0
#define SETTING_CONF_ARRAY05_SET15_DEF 				1
#define SETTING_CONF_ARRAY05_SET15_MAX				20
#define SETTING_CONF_ARRAY05_SET15_STEP				1
#define SETTING_CONF_ARRAY05_SET15_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY05_SET15_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY05_SET15_UPPER_LIMITER	0
/** Setting 16
  * @name Reserved */
#define SETTING_CONF_ARRAY05_SET16_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY05_SET16_MIN 				0
#define SETTING_CONF_ARRAY05_SET16_DEF 				1
#define SETTING_CONF_ARRAY05_SET16_MAX				20
#define SETTING_CONF_ARRAY05_SET16_STEP				1
#define SETTING_CONF_ARRAY05_SET16_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY05_SET16_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY05_SET16_UPPER_LIMITER	0
/** Setting 17
  * @name Reserved */
#define SETTING_CONF_ARRAY05_SET17_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY05_SET17_MIN 				0
#define SETTING_CONF_ARRAY05_SET17_DEF 				1
#define SETTING_CONF_ARRAY05_SET17_MAX				20
#define SETTING_CONF_ARRAY05_SET17_STEP				1
#define SETTING_CONF_ARRAY05_SET17_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY05_SET17_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY05_SET17_UPPER_LIMITER	0
/** Setting 18
  * @name Reserved */
#define SETTING_CONF_ARRAY05_SET18_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY05_SET18_MIN 				0
#define SETTING_CONF_ARRAY05_SET18_DEF 				1
#define SETTING_CONF_ARRAY05_SET18_MAX				20
#define SETTING_CONF_ARRAY05_SET18_STEP				1
#define SETTING_CONF_ARRAY05_SET18_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY05_SET18_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY05_SET18_UPPER_LIMITER	0
/** Setting 19
  * @name Reserved */
#define SETTING_CONF_ARRAY05_SET19_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY05_SET19_MIN 				0
#define SETTING_CONF_ARRAY05_SET19_DEF 				1
#define SETTING_CONF_ARRAY05_SET19_MAX				20
#define SETTING_CONF_ARRAY05_SET19_STEP				1
#define SETTING_CONF_ARRAY05_SET19_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY05_SET19_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY05_SET19_UPPER_LIMITER	0
/** Setting 20
  * @name Reserved */
#define SETTING_CONF_ARRAY05_SET20_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY05_SET20_MIN 				0
#define SETTING_CONF_ARRAY05_SET20_DEF 				1
#define SETTING_CONF_ARRAY05_SET20_MAX				20
#define SETTING_CONF_ARRAY05_SET20_STEP				1
#define SETTING_CONF_ARRAY05_SET20_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY05_SET20_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY05_SET20_UPPER_LIMITER	0
/** Setting 21
  * @name Reserved */
#define SETTING_CONF_ARRAY05_SET21_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY05_SET21_MIN 				0
#define SETTING_CONF_ARRAY05_SET21_DEF 				1
#define SETTING_CONF_ARRAY05_SET21_MAX				20
#define SETTING_CONF_ARRAY05_SET21_STEP				1
#define SETTING_CONF_ARRAY05_SET21_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY05_SET21_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY05_SET21_UPPER_LIMITER	0
/** Setting 22
  * @name Reserved */
#define SETTING_CONF_ARRAY05_SET22_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY05_SET22_MIN 				0
#define SETTING_CONF_ARRAY05_SET22_DEF 				1
#define SETTING_CONF_ARRAY05_SET22_MAX				20
#define SETTING_CONF_ARRAY05_SET22_STEP				1
#define SETTING_CONF_ARRAY05_SET22_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY05_SET22_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY05_SET22_UPPER_LIMITER	0
/** Setting 23
  * @name Reserved */
#define SETTING_CONF_ARRAY05_SET23_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY05_SET23_MIN 				0
#define SETTING_CONF_ARRAY05_SET23_DEF 				1
#define SETTING_CONF_ARRAY05_SET23_MAX				20
#define SETTING_CONF_ARRAY05_SET23_STEP				1
#define SETTING_CONF_ARRAY05_SET23_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY05_SET23_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY05_SET23_UPPER_LIMITER	0
/** Setting 24
  * @name Reserved */
#define SETTING_CONF_ARRAY05_SET24_TYPE				SETTING_INTEGER_MINUTE
#define SETTING_CONF_ARRAY05_SET24_MIN 				0
#define SETTING_CONF_ARRAY05_SET24_DEF 				1
#define SETTING_CONF_ARRAY05_SET24_MAX				20
#define SETTING_CONF_ARRAY05_SET24_STEP				1
#define SETTING_CONF_ARRAY05_SET24_LIMIT_TYPE		SETTING_NO_LIMIT
#define SETTING_CONF_ARRAY05_SET24_LOWER_LIMITER	0
#define SETTING_CONF_ARRAY05_SET24_UPPER_LIMITER	0

#endif /* __setting_config_h */

/* end of setting_config.h */
